# Everything .env.production needs — the rendered file is COMPLETE, nothing
# is hand-edited afterwards:
#   terraform output -raw env_production > ../../.env.production
#   unoverse deploy

locals {
  # Pooled URL for the services (transaction-mode PgBouncer; prepared statements off),
  # direct URL for migrations. BYO: your URL is used verbatim for both — you own the
  # pooling story against your own max_connections (INFRASTRUCTURE.md § BYO).
  # Managed modes (provisioned OR adopted existing cluster): the universe's own
  # user/db/pool were created on local.pg_cluster_id either way.
  pg_pooled = local.pg_managed ? "postgresql://${digitalocean_database_user.universe[0].name}:${digitalocean_database_user.universe[0].password}@${digitalocean_database_connection_pool.universe[0].private_host}:${digitalocean_database_connection_pool.universe[0].port}/${digitalocean_database_connection_pool.universe[0].name}?sslmode=require&pgbouncer=true" : var.byo_postgres_url
  pg_direct = local.pg_managed ? "postgresql://${digitalocean_database_user.universe[0].name}:${digitalocean_database_user.universe[0].password}@${local.pg_cluster_host}:${local.pg_cluster_port}/${digitalocean_database_db.universe[0].name}?sslmode=require" : var.byo_postgres_url

  # Redis is always ours — provisioned above, no BYO branch.
  redis_host     = digitalocean_database_cluster.redis.private_host
  redis_port     = digitalocean_database_cluster.redis.port
  redis_password = digitalocean_database_cluster.redis.password
  redis_tls      = true
}

output "deploy_host" {
  description = "The droplet's public IP (.env.production DEPLOY_HOST). Point api.<domain> at the LB IP, not this."
  value       = digitalocean_droplet.app.ipv4_address
}

output "lb_ip" {
  description = "The load balancer's IP — api.<domain>'s A record target (created automatically when manage_dns = true)."
  value       = digitalocean_loadbalancer.public.ip
}

output "canvas_url" {
  description = "Public Canvas URL (canvas_public = true only) — add it to the IdP's allowed origins."
  value       = var.canvas_public ? "https://canvas.${var.domain}:3001" : "canvas is admin-only (direct http://<droplet-ip>:3001 from admin_cidr)"
}

output "env_production" {
  sensitive   = true
  description = "Rendered .env.production — complete, write to a file and deploy"
  value       = <<-ENV
    # UNIVERSE (DigitalOcean) — generated by infra/digitalocean. COMPLETE:
    # do not hand-edit; change terraform.tfvars and re-render instead.

    # Deploy target
    DEPLOY_HOST=${digitalocean_droplet.app.ipv4_address}
    DEPLOY_USER=root

    # Container registry
    DOCR_TOKEN=${var.docr_token}

    # Database (pooled via managed PgBouncer, transaction mode — the Postgres law).
    # Migrations use the DIRECT url (db-setup prefers DATABASE_URL_DIRECT).
    DATABASE_URL=${local.pg_pooled}
    DATABASE_URL_DIRECT=${local.pg_direct}

    # Connection budget (INFRASTRUCTURE.md, size = ${var.size})
    DB_POOL_ENGINE=${local.s.pool_engine}
    DB_POOL_ENGINE_LEGACY=${local.s.pool_legacy}
    DB_POOL_MEMORY=${local.s.pool_memory}

    # Credential encryption at rest — per-deployment, generated by Terraform.
    # Back this up with the database (a DB backup is unreadable without it).
    CREDENTIAL_ENCRYPTION_KEY=${random_password.credential_key.result}

    # Redis (managed, TLS)
    REDIS_HOST=${local.redis_host}
    REDIS_PORT=${local.redis_port}
    REDIS_PASSWORD=${local.redis_password}
    REDIS_TLS=${local.redis_tls}
    REDIS_NAMESPACE=universe

    # OIDC — byo (Auth0 today): the tenant is authoritative for roles/permissions.
    AUTH_ISSUER=${var.auth_issuer}
    AUTH_CLIENT_ID=${var.auth_client_id}
    AUTH_AUDIENCE=${var.auth_audience}

    # Service keys
    OPENAI_API_KEY=${var.openai_api_key}
    HYPERBROWSER_API_KEY=${var.hyperbrowser_api_key}

    # Domain (api.${var.domain} → the load balancer, TLS terminated there)
    DOMAIN=${var.domain}
  ENV
}
