#!/usr/bin/env bash
# unoverse ground — prefill terraform.tfvars for your cloud ground
#
# The tfvars file is the ONE file a developer fills before `terraform apply`
# renders the complete .env.production. Most of its values are discoverable
# from the cloud CLI already on their machine, so this command discovers them
# and writes the file, leaving clearly marked FILL_ME lines for the handful
# only the developer knows (domain, IdP, service keys).
#
# Never clobbers: an existing terraform.tfvars is left alone.

_ground_my_ip() {
  curl -s --max-time 5 https://api.ipify.org 2>/dev/null || curl -s --max-time 5 https://ifconfig.me 2>/dev/null
}

_ground_do() {
  local dir="$ROOT/infra/digitalocean"
  local out="$dir/terraform.tfvars"

  if ! command -v doctl >/dev/null 2>&1; then
    fail "doctl is not installed"
    info "  brew install doctl        (macOS)"
    info "  https://docs.digitalocean.com/reference/doctl/how-to/install/"
    info "Then authenticate: doctl auth init"
    return 1
  fi
  if ! doctl account get >/dev/null 2>&1; then
    fail "doctl is not authenticated"
    info "Run: doctl auth init   (needs a DO API token from cloud.digitalocean.com/account/api)"
    return 1
  fi
  ok "doctl authenticated"

  local ip keys first_key pg_clusters pg_line
  ip=$(_ground_my_ip)
  [ -n "$ip" ] && ok "your IP: $ip" || warn "could not discover your IP (fill admin_cidr yourself)"

  keys=$(doctl compute ssh-key list --format Name --no-header 2>/dev/null)
  first_key=$(echo "$keys" | head -1)
  if [ -n "$first_key" ]; then
    ok "SSH key: $first_key$( [ "$(echo "$keys" | wc -l | xargs)" -gt 1 ] && echo " (of $(echo "$keys" | wc -l | xargs) — alternatives listed in the file)")"
  else
    warn "no SSH keys in the DO account. Add one first (doctl compute ssh-key import)"
  fi

  pg_clusters=$(doctl databases list --format Name,Engine --no-header 2>/dev/null | awk '$2=="pg"{print $1}')
  if [ -n "$pg_clusters" ]; then
    pg_line="# existing_pg_cluster_name = \"$(echo "$pg_clusters" | head -1)\"   # found in your account — uncomment to REUSE it (Terraform adds this universe's own db/user/pool)"
    ok "existing Postgres cluster found: $(echo "$pg_clusters" | head -1) (reuse offered in the file)"
  else
    pg_line="# existing_pg_cluster_name = \"...\"   # none found in your account — leave unset to provision a fresh cluster"
    info "no existing Postgres cluster. Terraform will provision one"
  fi

  cat > "$out" <<EOF
# Generated by \`unoverse ground do\` on $(date +%Y-%m-%d). Discovered values are
# prefilled; every FILL_ME needs YOUR value before \`terraform apply\`.
# Token: set DIGITALOCEAN_TOKEN in the environment (preferred) or do_token here.

region       = "lon1"                    # doctl compute region list
name         = "universe-poc"
size         = "small"                   # small (POC) | medium | large
admin_cidr   = "${ip:-FILL_ME}${ip:+/32}"        # YOUR IP — SSH + Dozzle only
ssh_key_name = "${first_key:-FILL_ME}"   # must already exist in the DO account
$(echo "$keys" | tail -n +2 | sed 's/^/# ssh_key_name alternative: /')
domain       = "FILL_ME"                 # api.<domain> → the LB
manage_dns   = false                     # true only if the domain's DNS is on DO

# ⚠ The managed Let's Encrypt certificate requires the domain's DNS to be HOSTED
# on DigitalOcean (registrar can stay GoDaddy etc. — point the nameservers at
# ns1/ns2/ns3.digitalocean.com and add the domain under Networking). Then
# manage_dns = true also creates the records for you.

# POC ONLY: public Canvas at https://api.<domain>:3001 (a second port on the ONE LB).
# Add that URL to the IdP's allowed origins. Default false = admin-only.
canvas_public = true

# Auth — byo-oidc: roles/permissions live in YOUR IdP tenant.
auth_issuer    = "FILL_ME"               # e.g. https://your-tenant.auth0.com
auth_client_id = "FILL_ME"
auth_audience  = "gravity-api"

# Service secrets — with these set, the rendered .env.production is COMPLETE.
docr_token     = "FILL_ME"               # read-only registry token from your Unoverse admin
openai_api_key = "FILL_ME"
# hyperbrowser_api_key = ""              # optional — page intelligence

# Postgres — leave unset to provision a fresh cluster:
$pg_line
#   Or a fully external database, used verbatim:
# byo_postgres_url = "postgresql://user:pass@host:5432/db?sslmode=require"

# Redis: always provisioned by Terraform (Managed Redis, TLS). Not configurable.

# The rendered output (terraform output -raw env_production > ../../.env.production)
# IS your universe's secrets, including the MASTER KEY (CREDENTIAL_ENCRYPTION_KEY)
# that locks every credential users save in the platform. If it's lost, no backup
# can bring them back. Never commit it; keep a safe copy with your database backups.
EOF

  # Blank alternative-keys line when there is only one key.
  sed -i '' '/^# ssh_key_name alternative: *$/d' "$out" 2>/dev/null || sed -i '/^# ssh_key_name alternative: *$/d' "$out"
  ok "wrote infra/digitalocean/terraform.tfvars"
}

_ground_aws() {
  local dir="$ROOT/infra/aws"
  local out="$dir/terraform.tfvars"

  if ! command -v aws >/dev/null 2>&1; then
    fail "the AWS CLI is not installed"
    info "  brew install awscli       (macOS)"
    info "  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    info "Then authenticate: aws configure"
    return 1
  fi
  if ! aws sts get-caller-identity >/dev/null 2>&1; then
    fail "the AWS CLI is not authenticated"
    info "Run: aws configure   (or set AWS_PROFILE to a working profile)"
    return 1
  fi
  ok "AWS CLI authenticated ($(aws sts get-caller-identity --query Account --output text 2>/dev/null))"

  local ip region keys first_key zones zone_id zone_domain
  ip=$(_ground_my_ip)
  [ -n "$ip" ] && ok "your IP: $ip" || warn "could not discover your IP (fill admin_cidr yourself)"

  region=$(aws configure get region 2>/dev/null)
  [ -n "$region" ] && ok "region: $region" || { region="us-east-1"; info "no default region configured. Using us-east-1"; }

  keys=$(aws ec2 describe-key-pairs --query 'KeyPairs[].KeyName' --output text 2>/dev/null | tr '\t' '\n')
  first_key=$(echo "$keys" | head -1)
  if [ -n "$first_key" ]; then
    ok "EC2 key pair: $first_key"
  else
    warn "no EC2 key pairs in $region. Create one first (aws ec2 create-key-pair)"
  fi

  # Exactly one hosted zone → we know the domain AND the zone id (auto DNS + cert validation).
  zones=$(aws route53 list-hosted-zones --query 'HostedZones[].[Id,Name]' --output text 2>/dev/null)
  if [ "$(echo "$zones" | grep -c .)" = "1" ]; then
    zone_id=$(echo "$zones" | awk '{print $1}' | sed 's|/hostedzone/||')
    zone_domain=$(echo "$zones" | awk '{print $2}' | sed 's/\.$//')
    ok "Route53 zone: $zone_domain ($zone_id): DNS + certificate validation will be automatic"
  elif [ -n "$zones" ]; then
    info "multiple Route53 zones. Pick one in the file (listed there)"
  fi

  cat > "$out" <<EOF
# Generated by \`unoverse ground aws\` on $(date +%Y-%m-%d). Discovered values are
# prefilled; every FILL_ME needs YOUR value before \`terraform apply\`.

region       = "$region"
name         = "universe-poc"
admin_cidr   = "${ip:-FILL_ME}${ip:+/32}"       # YOUR IP — the only SSH source
ssh_key_name = "${first_key:-FILL_ME}"  # must already exist in the region
admin_email  = "FILL_ME"                # initial admin (Cognito user, all roles; invite emailed)
size         = "small"                  # small (POC) | medium | large
domain       = "${zone_domain:-FILL_ME}"        # api.<domain> → the ALB

# OPTIONAL: the domain's Route53 hosted zone id — set and Terraform creates the
# DNS records AND auto-validates the certificate.
$( if [ -n "$zone_id" ]; then echo "route53_zone_id = \"$zone_id\""; else echo "# route53_zone_id = \"Z0123456789ABC\""; fi )
$( [ -n "$zones" ] && [ -z "$zone_id" ] && echo "$zones" | awk '{gsub("/hostedzone/","",$1); print "# zone: " $2 " → " $1}' )

# POC ONLY: public Canvas at https://unoverse.<domain> — a host rule on the ONE
# ALB. Add the URL to oauth origins.
canvas_public = true

# Service secrets — with these set, the rendered .env.production is COMPLETE.
docr_token     = "FILL_ME"              # read-only registry token from your Unoverse admin
openai_api_key = "FILL_ME"
# hyperbrowser_api_key = ""             # optional — page intelligence

oauth_callback_urls = [
$( if [ -n "$zone_domain" ]; then echo "  \"https://$zone_domain\","; else echo "  \"https://FILL_ME\","; fi )
  "http://localhost:5173", # local Studio/Canvas dev against this universe
]

# RBAC roles (noun:verb). Each becomes a Cognito group; put a user in the group
# and the role rides their token.
roles = [
  "workflow:author",     # build and test workflows (builder gate — ENFORCED)
  "marketplace:publish", # publish assets to this universe (publish gate — ENFORCED)
  "workflow:promote",    # promote a draft to active / go-live (declared only)
  "admin:access",        # admin to Unoverse Canvas (declared only)
]

# The rendered output (terraform output -raw env_production > ../../.env.production)
# IS your universe's secrets, including the MASTER KEY (CREDENTIAL_ENCRYPTION_KEY)
# that locks every credential users save in the platform. If it's lost, no backup
# can bring them back. Never commit it; keep a safe copy with your database backups.
EOF

  ok "wrote infra/aws/terraform.tfvars"
}

cmd_ground() {
  local which="${1:-}"

  # No argument: pick the ground by which CLI is present and authenticated.
  if [ -z "$which" ]; then
    local has_do=false has_aws=false
    command -v doctl >/dev/null 2>&1 && doctl account get >/dev/null 2>&1 && has_do=true
    command -v aws >/dev/null 2>&1 && aws sts get-caller-identity >/dev/null 2>&1 && has_aws=true
    if $has_do && $has_aws; then
      fail "both doctl and the AWS CLI are authenticated. Say which ground:"
      info "  ./unoverse ground do    or    ./unoverse ground aws"
      return 1
    elif $has_do; then which="do"
    elif $has_aws; then which="aws"
    else
      fail "no authenticated cloud CLI found"
      info "DigitalOcean:  brew install doctl && doctl auth init   → ./unoverse ground do"
      info "AWS:           brew install awscli && aws configure    → ./unoverse ground aws"
      return 1
    fi
  fi

  case "$which" in
    do|digitalocean)
      banner "Prefill your DigitalOcean ground"
      [ -f "$ROOT/infra/digitalocean/terraform.tfvars" ] && { fail "infra/digitalocean/terraform.tfvars already exists. Edit it, or delete it to regenerate"; return 1; }
      _ground_do || return 1
      echo ""
      info "Next: fill every FILL_ME in infra/digitalocean/terraform.tfvars, then"
      info "  cd infra/digitalocean && terraform init && terraform apply"
      info "  terraform output -raw env_production > ../../.env.production"
      info "  cd ../.. && ./unoverse deploy"
      ;;
    aws)
      banner "Prefill your AWS ground"
      [ -f "$ROOT/infra/aws/terraform.tfvars" ] && { fail "infra/aws/terraform.tfvars already exists. Edit it, or delete it to regenerate"; return 1; }
      _ground_aws || return 1
      echo ""
      info "Next: fill every FILL_ME in infra/aws/terraform.tfvars, then"
      info "  cd infra/aws && terraform init && terraform apply"
      info "  terraform output -raw env_production > ../../.env.production"
      info "  cd ../.. && ./unoverse deploy"
      ;;
    *)
      fail "unknown ground: $which (use: do | aws)"
      return 1
      ;;
  esac
}
